[project]
name = "static"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "jsbeautifier>=1.15.4",
    "jsmin>=3.0.1",
    "jsoncomment>=0.4.2",
    "jstyleson>=0.0.2",
    "retirejs>=1.5",
    "tldextract>=5.3.1",
]
